#!/usr/bin/env python3
"""
Embed web assets as C arrays with gzip compression.

Usage:
    python3 embed_assets.py <dist_dir> <output.c>

Example:
    python3 embed_assets.py frontend/dist src/assets.c
"""

import sys
import gzip
from pathlib import Path


MIME_TYPES = {
    '.html': 'text/html',
    '.js': 'application/javascript',
    '.css': 'text/css',
    '.json': 'application/json',
    '.svg': 'image/svg+xml',
    '.png': 'image/png',
    '.ico': 'image/x-icon',
}


def get_mime_type(path: Path) -> str:
    return MIME_TYPES.get(path.suffix.lower(), 'application/octet-stream')


def sanitize_name(path: str) -> str:
    """Convert path to valid C identifier."""
    return path.replace('/', '_').replace('.', '_').replace('-', '_').lstrip('_')


def bytes_to_c_array(data: bytes) -> str:
    """Convert bytes to C array initializer."""
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_values = ', '.join(f'0x{b:02x}' for b in chunk)
        lines.append(f'    {hex_values},')
    return '\n'.join(lines)


def main():
    if len(sys.argv) < 3:
        print(f"Usage: {sys.argv[0]} <dist_dir> <output.c>", file=sys.stderr)
        sys.exit(1)

    dist_dir = Path(sys.argv[1])
    output_file = Path(sys.argv[2])

    if not dist_dir.exists():
        print(f"ERROR: {dist_dir} not found", file=sys.stderr)
        sys.exit(1)

    assets = []

    # Collect all files
    for file_path in sorted(dist_dir.rglob('*')):
        if file_path.is_dir():
            continue

        rel_path = '/' + str(file_path.relative_to(dist_dir))
        content = file_path.read_bytes()
        compressed = gzip.compress(content, compresslevel=9)

        assets.append({
            'path': rel_path,
            'name': sanitize_name(rel_path),
            'mime': get_mime_type(file_path),
            'data': compressed,
            'original_size': len(content),
        })

        print(f"  {rel_path}: {len(content)} -> {len(compressed)} bytes "
              f"({100*len(compressed)//len(content)}%)")

    # Generate C file
    output_lines = [
        '/* Auto-generated by embed_assets.py - DO NOT EDIT */',
        '#include "assets.h"',
        '#include <string.h>',
        '',
    ]

    # Data arrays
    for asset in assets:
        output_lines.append(f'static const uint8_t asset_{asset["name"]}[] = {{')
        output_lines.append(bytes_to_c_array(asset['data']))
        output_lines.append('};')
        output_lines.append('')

    # Asset table
    output_lines.append('static const webui_asset_t s_assets[] = {')

    # Add root alias for index.html
    index_asset = next((a for a in assets if a['path'] == '/index.html'), None)
    if index_asset:
        output_lines.append(f'    {{"/", "{index_asset["mime"]}", '
                          f'asset_{index_asset["name"]}, {len(index_asset["data"])}, true}},')

    for asset in assets:
        output_lines.append(f'    {{"{asset["path"]}", "{asset["mime"]}", '
                          f'asset_{asset["name"]}, {len(asset["data"])}, true}},')

    output_lines.append('    {NULL, NULL, NULL, 0, false},  /* Terminator */')
    output_lines.append('};')
    output_lines.append('')

    # Functions
    output_lines.extend([
        f'static const size_t s_asset_count = {len(assets) + (1 if index_asset else 0)};',
        '',
        'const webui_asset_t *webui_find_asset(const char *path) {',
        '    for (size_t i = 0; s_assets[i].path != NULL; i++) {',
        '        if (strcmp(s_assets[i].path, path) == 0) {',
        '            return &s_assets[i];',
        '        }',
        '    }',
        '    return NULL;',
        '}',
        '',
        'size_t webui_get_asset_count(void) {',
        '    return s_asset_count;',
        '}',
        '',
        'const webui_asset_t *webui_get_assets(void) {',
        '    return s_assets;',
        '}',
    ])

    output_file.write_text('\n'.join(output_lines) + '\n')
    print(f"\nGenerated {output_file} with {len(assets)} assets")


if __name__ == '__main__':
    main()
