/**
 * @file log_tags.h
 * @brief Auto-generated list of ESP_LOG tags for tab completion
 *
 * DO NOT EDIT - Generated by scripts/gen_log_tags.py during build
 */

#ifndef LOG_TAGS_H
#define LOG_TAGS_H

#include <stddef.h>

static const char *LOG_TAGS[] = {
    "config_nvs",
    "esp_netif",
    "esp_tls",
    "http_client",
    "main",
    "mqtt",
    "usb_cdc",
    "usb_console",
    "usb_log",
    "usb_uf2",
    "usb_winkeyer",
    "wifi",
};

#define LOG_TAGS_COUNT (sizeof(LOG_TAGS) / sizeof(LOG_TAGS[0]))

#endif /* LOG_TAGS_H */
