/**
 * @file provisioning_html.c
 * @brief Embedded HTML/CSS for provisioning web UI
 *
 * All HTML is embedded as C strings for zero external dependencies.
 */

/* Main configuration form */
static const char PROV_HTML_FORM[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>CW Keyer Setup</title>\n"
    "  <style>\n"
    "    * { box-sizing: border-box; }\n"
    "    body {\n"
    "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
    "      max-width: 420px;\n"
    "      margin: 0 auto;\n"
    "      padding: 20px;\n"
    "      background: #f5f5f5;\n"
    "      color: #333;\n"
    "    }\n"
    "    h1 {\n"
    "      text-align: center;\n"
    "      color: #2c3e50;\n"
    "      margin-bottom: 30px;\n"
    "      font-size: 1.5em;\n"
    "    }\n"
    "    .card {\n"
    "      background: white;\n"
    "      border-radius: 12px;\n"
    "      padding: 24px;\n"
    "      box-shadow: 0 2px 8px rgba(0,0,0,0.1);\n"
    "    }\n"
    "    label {\n"
    "      display: block;\n"
    "      margin: 16px 0 6px;\n"
    "      font-weight: 500;\n"
    "      color: #555;\n"
    "    }\n"
    "    input, select {\n"
    "      width: 100%;\n"
    "      padding: 12px;\n"
    "      border: 1px solid #ddd;\n"
    "      border-radius: 8px;\n"
    "      font-size: 16px;\n"
    "      transition: border-color 0.2s;\n"
    "    }\n"
    "    input:focus, select:focus {\n"
    "      outline: none;\n"
    "      border-color: #3498db;\n"
    "    }\n"
    "    .ssid-group {\n"
    "      display: flex;\n"
    "      gap: 8px;\n"
    "    }\n"
    "    .ssid-group select { flex: 1; }\n"
    "    .ssid-group button {\n"
    "      padding: 12px 16px;\n"
    "      background: #ecf0f1;\n"
    "      border: 1px solid #ddd;\n"
    "      border-radius: 8px;\n"
    "      cursor: pointer;\n"
    "    }\n"
    "    button[type=\"submit\"] {\n"
    "      width: 100%;\n"
    "      padding: 14px;\n"
    "      margin-top: 24px;\n"
    "      background: #3498db;\n"
    "      color: white;\n"
    "      border: none;\n"
    "      border-radius: 8px;\n"
    "      font-size: 16px;\n"
    "      font-weight: 600;\n"
    "      cursor: pointer;\n"
    "      transition: background 0.2s;\n"
    "    }\n"
    "    button[type=\"submit\"]:hover { background: #2980b9; }\n"
    "    button[type=\"submit\"]:disabled {\n"
    "      background: #bdc3c7;\n"
    "      cursor: not-allowed;\n"
    "    }\n"
    "    .error {\n"
    "      color: #e74c3c;\n"
    "      font-size: 0.85em;\n"
    "      margin-top: 4px;\n"
    "    }\n"
    "    .hint {\n"
    "      color: #7f8c8d;\n"
    "      font-size: 0.8em;\n"
    "      margin-top: 4px;\n"
    "    }\n"
    "    .spinner {\n"
    "      display: inline-block;\n"
    "      width: 16px;\n"
    "      height: 16px;\n"
    "      border: 2px solid #fff;\n"
    "      border-top-color: transparent;\n"
    "      border-radius: 50%;\n"
    "      animation: spin 0.8s linear infinite;\n"
    "      margin-right: 8px;\n"
    "      vertical-align: middle;\n"
    "    }\n"
    "    @keyframes spin { to { transform: rotate(360deg); } }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <h1>CW Keyer Setup</h1>\n"
    "  <div class=\"card\">\n"
    "    <form id=\"setup\" action=\"/save\" method=\"POST\">\n"
    "      <label for=\"ssid-select\">WiFi Network</label>\n"
    "      <div class=\"ssid-group\">\n"
    "        <select id=\"ssid-select\" onchange=\"ssidSelected()\">\n"
    "          <option value=\"\">Scanning...</option>\n"
    "        </select>\n"
    "        <button type=\"button\" onclick=\"rescan()\">Scan</button>\n"
    "      </div>\n"
    "      <input type=\"text\" name=\"ssid\" id=\"ssid\" placeholder=\"Or type network name\" style=\"margin-top:8px\">\n"
    "\n"
    "      <label for=\"password\">WiFi Password</label>\n"
    "      <input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Leave empty for open networks\">\n"
    "      <div class=\"error\" id=\"password-error\"></div>\n"
    "      <div class=\"hint\">Minimum 8 characters for secured networks</div>\n"
    "\n"
    "      <label for=\"callsign\">Your Callsign</label>\n"
    "      <input type=\"text\" name=\"callsign\" id=\"callsign\" placeholder=\"e.g., IU4AAA\" required \n"
    "             pattern=\"[A-Za-z0-9/]{3,10}\" style=\"text-transform: uppercase;\">\n"
    "      <div class=\"error\" id=\"callsign-error\"></div>\n"
    "\n"
    "      <label for=\"theme\">App Theme</label>\n"
    "      <select name=\"theme\" id=\"theme\">\n"
    "        <option value=\"0\">Light</option>\n"
    "        <option value=\"1\">Dark</option>\n"
    "      </select>\n"
    "\n"
    "      <button type=\"submit\" id=\"submit-btn\">Save Configuration</button>\n"
    "    </form>\n"
    "  </div>\n"
    "\n"
    "  <script>\n"
    "    function scanNetworks() {\n"
    "      const sel = document.getElementById('ssid-select');\n"
    "      sel.innerHTML = '<option value=\"\">Scanning...</option>';\n"
    "      sel.disabled = true;\n"
    "\n"
    "      fetch('/scan')\n"
    "        .then(r => r.json())\n"
    "        .then(networks => {\n"
    "          sel.innerHTML = '<option value=\"\">-- Select Network --</option>';\n"
    "          networks.sort((a, b) => b.rssi - a.rssi);\n"
    "          networks.forEach(n => {\n"
    "            const lock = n.auth ? ' [secured]' : ' [open]';\n"
    "            const signal = n.rssi > -50 ? 'Strong' : n.rssi > -70 ? 'Good' : 'Weak';\n"
    "            sel.innerHTML += '<option value=\"' + n.ssid + '\">' + n.ssid + ' (' + signal + ')' + lock + '</option>';\n"
    "          });\n"
    "          sel.disabled = false;\n"
    "        })\n"
    "        .catch(() => {\n"
    "          sel.innerHTML = '<option value=\"\">Scan failed - type manually</option>';\n"
    "          sel.disabled = false;\n"
    "        });\n"
    "    }\n"
    "\n"
    "    function ssidSelected() {\n"
    "      const sel = document.getElementById('ssid-select');\n"
    "      const input = document.getElementById('ssid');\n"
    "      if (sel.value) {\n"
    "        input.value = sel.value;\n"
    "      }\n"
    "    }\n"
    "\n"
    "    function rescan() {\n"
    "      scanNetworks();\n"
    "    }\n"
    "\n"
    "    // Initial scan on load\n"
    "    scanNetworks();\n"
    "\n"
    "    // Form validation\n"
    "    document.getElementById('setup').onsubmit = function(e) {\n"
    "      const ssid = document.getElementById('ssid').value.trim();\n"
    "      const pw = document.getElementById('password').value;\n"
    "      const call = document.getElementById('callsign').value.trim().toUpperCase();\n"
    "      let valid = true;\n"
    "\n"
    "      // Update callsign to uppercase\n"
    "      document.getElementById('callsign').value = call;\n"
    "\n"
    "      // Validate SSID\n"
    "      if (!ssid) {\n"
    "        alert('Please select or enter a WiFi network');\n"
    "        valid = false;\n"
    "      }\n"
    "\n"
    "      // Validate password\n"
    "      if (pw.length > 0 && pw.length < 8) {\n"
    "        document.getElementById('password-error').textContent = 'Password must be at least 8 characters';\n"
    "        valid = false;\n"
    "      } else {\n"
    "        document.getElementById('password-error').textContent = '';\n"
    "      }\n"
    "\n"
    "      // Validate callsign\n"
    "      if (!/^[A-Za-z0-9/]{3,10}$/.test(call)) {\n"
    "        document.getElementById('callsign-error').textContent = 'Enter a valid callsign (3-10 characters)';\n"
    "        valid = false;\n"
    "      } else {\n"
    "        document.getElementById('callsign-error').textContent = '';\n"
    "      }\n"
    "\n"
    "      if (!valid) {\n"
    "        e.preventDefault();\n"
    "        return false;\n"
    "      }\n"
    "\n"
    "      // Show saving indicator\n"
    "      const btn = document.getElementById('submit-btn');\n"
    "      btn.innerHTML = '<span class=\"spinner\"></span>Saving...';\n"
    "      btn.disabled = true;\n"
    "      return true;\n"
    "    };\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

/* Success page with reboot countdown */
static const char PROV_HTML_SUCCESS[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "  <meta charset=\"UTF-8\">\n"
    "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "  <title>Configuration Saved</title>\n"
    "  <style>\n"
    "    body {\n"
    "      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n"
    "      max-width: 420px;\n"
    "      margin: 0 auto;\n"
    "      padding: 40px 20px;\n"
    "      text-align: center;\n"
    "      background: #f5f5f5;\n"
    "    }\n"
    "    .success-icon {\n"
    "      font-size: 64px;\n"
    "      margin-bottom: 20px;\n"
    "    }\n"
    "    h1 {\n"
    "      color: #27ae60;\n"
    "      margin-bottom: 10px;\n"
    "    }\n"
    "    p {\n"
    "      color: #666;\n"
    "      font-size: 1.1em;\n"
    "    }\n"
    "    .countdown {\n"
    "      font-size: 3em;\n"
    "      font-weight: bold;\n"
    "      color: #3498db;\n"
    "      margin: 20px 0;\n"
    "    }\n"
    "    .note {\n"
    "      margin-top: 30px;\n"
    "      padding: 15px;\n"
    "      background: #fff;\n"
    "      border-radius: 8px;\n"
    "      color: #555;\n"
    "      font-size: 0.9em;\n"
    "    }\n"
    "  </style>\n"
    "</head>\n"
    "<body>\n"
    "  <div class=\"success-icon\">&#10003;</div>\n"
    "  <h1>Configuration Saved!</h1>\n"
    "  <p>Your CW Keyer is being configured.</p>\n"
    "  <div class=\"countdown\" id=\"countdown\">3</div>\n"
    "  <p>Rebooting...</p>\n"
    "  <div class=\"note\">\n"
    "    After reboot, connect to your WiFi network and access the keyer at its new IP address.\n"
    "  </div>\n"
    "  <script>\n"
    "    let count = 3;\n"
    "    const el = document.getElementById('countdown');\n"
    "    setInterval(() => {\n"
    "      count--;\n"
    "      if (count >= 0) {\n"
    "        el.textContent = count;\n"
    "      } else {\n"
    "        el.textContent = '...';\n"
    "      }\n"
    "    }, 1000);\n"
    "  </script>\n"
    "</body>\n"
    "</html>\n";

const char *prov_get_html_form(void)
{
    return PROV_HTML_FORM;
}

const char *prov_get_html_success(void)
{
    return PROV_HTML_SUCCESS;
}
